### PR TITLE
Added the two images to the canvas

### PR DESCRIPTION
**Pull request by gustafsonb**
I think it's ready

### CODE REVIEW

**Comment by brockers** [comment]
Please put "var sources" at the top of the application.js file (right under the htmlCanvas declaration.)

**Comment by brockers** [comment]
canvas and context on lines 59 & 60 are duplicates and can be removed.  The program works without them because the one on line 8 works.

**Comment by brockers** [comment]
TABS... for the love of all things holy... TABS!!!!   I will kill a small kitten for every missing tab you have in your code you evil son-of-a-$(_$(_#

**Comment by gustafsonb** [comment]
Okay you may check it out now!

**Pull request merged**
